name: Build and Deploy Client to gh-pages

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Install npm 7
        run: npm install -g npm@7

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build project
        run: npm run build
        env:
          SKIP_PREFLIGHT_CHECK: true
          REACT_APP_API_ROOT: https://monopoly-money-server.herokuapp.com
          REACT_APP_GOOGLE_ANALYTICS_TRACKING_ID: UA-117153268-5
          REACT_APP_API_UNREACHABLE_ERROR_MESSAGE: "Unable to communicate with server.\nSince this is publicly hosted, we may have run out of minutes on the server.\nThis should be running again next month when the time is reset."
          CI: false
          GENERATE_SOURCEMAP: false

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/client/build
